### ISSUE TITLE
Depend on CoreCompat.System.Drawing instead of System.Drawing for .net core compatibility

### ISSUE THREAD

**Issue by thiagomajesk** [dmester/jdenticon-net#2]
Depending on Bitmap makes the Bitmap extension unavailable for .net core projects. Please consider replacing it with another alternative as seen here: 
https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/

**Comment by dmester** [comment]
There are no dependencies to System.Drawing except from in the [Jdenticon.Gdi](https://www.nuget.org/packages/Jdenticon.Gdi/) package, which is only intended for legacy WinForms applications. You should be able to use the [SaveAsPng](https://jdenticon.com/net-api/Methods_T_Jdenticon_PngExtensions.html) and [SaveAsSvg/ToSvg](https://jdenticon.com/net-api/Methods_T_Jdenticon_SvgExtensions.html) extension methods on .NET Core by only including the [Jdenticon-net](https://www.nuget.org/packages/Jdenticon-net/) package. See the compatibility chart below.

Extension Method | Package | Supports .NET Core
------------ | ------------- | --------------
[Identicon.Draw(Graphics, Rectangle)](https://jdenticon.com/net-api/Overload_Jdenticon_GdiExtensions_Draw.html) | [Jdenticon.Gdi](https://www.nuget.org/packages/Jdenticon.Gdi/) | 
[Identicon.Draw(DrawingContext, Rectangle)](https://jdenticon.com/net-api/Overload_Jdenticon_WpfExtensions_Draw.html) | [Jdenticon.Wpf](https://www.nuget.org/packages/Jdenticon.Wpf/) |
[Identicon.SaveAsEmf](https://jdenticon.com/net-api/Overload_Jdenticon_GdiExtensions_SaveAsEmf.html) | [Jdenticon.Gdi](https://www.nuget.org/packages/Jdenticon.Gdi/) | 
[Identicon.SaveAsPng](https://jdenticon.com/net-api/Overload_Jdenticon_PngExtensions_SaveAsPng.html) | [Jdenticon-net](https://www.nuget.org/packages/Jdenticon-net/) | ✅
[Identicon.SaveAsSvg](https://jdenticon.com/net-api/Overload_Jdenticon_SvgExtensions_SaveAsSvg.html) | [Jdenticon-net](https://www.nuget.org/packages/Jdenticon-net/) | ✅
[Identicon.ToBitmap](https://jdenticon.com/net-api/M_Jdenticon_GdiExtensions_ToBitmap.html) | [Jdenticon.Gdi](https://www.nuget.org/packages/Jdenticon.Gdi/) | 
[Identicon.ToSvg](https://jdenticon.com/net-api/Overload_Jdenticon_SvgExtensions_ToSvg.html) | [Jdenticon-net](https://www.nuget.org/packages/Jdenticon-net/) | ✅
[Identicon.ToVisual](https://jdenticon.com/net-api/M_Jdenticon_WpfExtensions_ToVisual.html) | [Jdenticon.Wpf](https://www.nuget.org/packages/Jdenticon.Wpf/) | 

What is your use case? Do you need an explicit Bitmap extension on .NET Core?

**Comment by thiagomajesk** [comment]
@dmester 
I was talking exactly about `Jdenticon.Gdi` extensions - I didn't know this was specific for winforms...
But I suppose this could be provided in the core lib as an alternative for people wanting to work with Bitmap, no!?

**Comment by dmester** [comment]
I guess System.Drawing.Common is a better alternative than CoreCompat.System.Drawing these days. I need to do some further investigation, I will come back to you.

**Comment by dmester** [comment]
Support for System.Drawing.Common was added in release 2.2.0.
