### ISSUE TITLE
Update Asp.Net Mvc Html extensions to support Asp.Net Core

### ISSUE THREAD

**Issue by thiagomajesk** [dmester/jdenticon-net#3]
Or create a tag helper for asp.net core if the intention is to still keep compatibility with older versions of Asp.Net Mvc.

**Comment by dmester** [comment]
Thanks for your suggestion, seems like a good idea! I will plan it for the next release.

**Comment by dmester** [comment]
Support for ASP.NET Core was added in release 2.2.0.
