### ISSUE TITLE
Generate avatar using initials

### ISSUE THREAD

**Issue by JobaDiniz** [dmester/jdenticon-net#5]
Similar to Microsoft Teams and TFS.
When user does not upload its avatar, the system generates one based on the user name, using their initials

![image](https://user-images.githubusercontent.com/165290/66041630-ab602680-e4f0-11e9-9f6f-82954804a45d.png)

**Comment by dmester** [comment]
Thank you for your suggestion, but I'm afraid there are no plans to add support for other kinds of avatars to Jdenticon.

Maybe this library provides what you are looking for?
https://github.com/mgibas/avatarator
